### ISSUE TITLE
pr0gramm API

### ISSUE THREAD

**Issue by Henning-K** [hoshsadiq/adblock-nocoin-list#8] opened 2017-09-26 08:07 UTC
Blocking the miner scripts on pr0gramm.com is quite good but blocking pr0gramm.com/api/ makes the whole image board non functional which is most likely not the intended behaviour.

**Comment by hoshsadiq** [comment] 2017-09-26 10:07
Indeed not intended behaviour! Merged.

**Closed by hoshsadiq** 2017-09-26 10:07 UTC
