### ISSUE TITLE
a-o.ninja

### ISSUE THREAD

**Issue by KonoromiHimaries** [hoshsadiq/adblock-nocoin-list#62] opened 2017-12-03 16:20 UTC
![2017-12-03 17_11_52-menedzer zadan](https://user-images.githubusercontent.com/5884000/33527275-2acaa5fa-d84e-11e7-9ca9-e38ff9380aa5.png)

![2017-12-03 17_11_34-highschool dxd new 08 pl online hd a-o ninja anime online pl 2018 emitowane](https://user-images.githubusercontent.com/5884000/33527277-3326feec-d84e-11e7-8f93-cf86ab452221.png)
`https://a-o.ninja/anime/high-school-dxd-2/8`

https://github.com/MajkiIT/polish-ads-filter/issues/4701

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.118
chrome 62.0.3202.94

**Comment by hoshsadiq** [comment] 2017-12-07 08:29
Hi, `a-o.ninja` uses coinhive, which is already on the block list. No need to block anything else.

**Comment by mat41997** [comment] 2017-12-07 08:54
@hoshsadiq my cpu he disagrees with you

**Comment by hoshsadiq** [comment] 2017-12-07 08:58
Ok! I will check again.

**Comment by MajkiIT** [comment] 2017-12-09 13:47
It's the same like this https://github.com/hoshsadiq/adblock-nocoin-list/issues/64 . They use links from openkatalog.com , but today it's OK.

**Comment by hoshsadiq** [comment] 2017-12-09 16:21
They smart! They're somehow bypassing something in one way or another and it kicks in a bit late. I will add a filter asap. 

<img width="457" alt="image" src="https://user-images.githubusercontent.com/600045/33797273-f63d5aea-dcfc-11e7-95c2-e9f5ba1485dc.png">

**Comment by hoshsadiq** [comment] 2017-12-09 16:32
I've added a new filter which seems to work for me. If you can test it and report back.

**Comment by hoshsadiq** [comment] 2017-12-10 16:14
I will close this for now. Feel free to comment if the issue isn't solved.

**Comment by MajkiIT** [comment] 2017-12-11 21:12
Today is https://subloader.cf/heywhatsupgirl/backup/ 
`||subloader.cf/*$subdocument,`

**Comment by SMed79** [comment] 2017-12-11 23:31
```
/^((?!(^https?):\/\/vidfile\.net\/|(^https?):\/\/www\.youtube\.com\/|(^https?):\/\/openload\.co\/|(^https?):\/\/docs\.google\.com\/|(^https?):\/\/video\.sibnet\.ru\/|(^https?):\/\/oload\.stream\/|(^https?):\/\/streamango\.com\/|(^https?):\/\/vidlox\.tv\/|(^https?):\/\/www\.rapidvideo\.com\/|(^https?):\/\/tune\.pk\/|(^https?):\/\/www\.dailymotion\.com\/|(^https?):\/\/estream\.to\/).)*$/$subdocument,domain=a-o.ninja|vidfile.net
```

**Comment by hoshsadiq** [comment] 2017-12-12 11:12
Add a slight variation of @SMed79

**Comment by hoshsadiq** [comment] 2017-12-22 17:53
Considering there has been no other reports of this, I think it's safe to close. Please feel free to post here again if it's not.

**Closed by hoshsadiq** 2017-12-22 17:53 UTC

**Comment by KonoromiHimaries** [comment] 2018-07-29 13:54
https://github.com/MajkiIT/polish-ads-filter/issues/8512#issuecomment-408678946

**Comment by KonoromiHimaries** [comment] 2018-07-29 13:55
@smed79

**Comment by smed79** [comment] 2018-07-30 14:23
@KonoromiHimaries 

- no link please, take a little time to explain the issue here (in English)
- fyi, "nocoin list" does not care about anti adblock
