### ISSUE TITLE
activating the list causes an anti adblock message on mashable.com

### ISSUE THREAD

**Issue by elypter** [hoshsadiq/adblock-nocoin-list#219] opened 2018-05-06 15:28 UTC
### Website with example

https://mashable.com/2018/02/14/elon-musk-capitalism-spacex/#vxWLF.V7iaq6

### Screenshot

http://i.imgur.com/3NiokSL.png

**Comment by smed79** [comment] 2018-05-06 16:16
1. This list deal with mining stuff, we do not fix anti adblock mechanism.
2. The issue you are reporting here is not caused by nocoin filter list.

Search from your side which list is blocking [https://www.adiode.com/http](http://i.imgur.com/RGrqHKV.png).

**Comment by hoshsadiq** [comment] 2018-05-09 20:42
Closing as no additional info given, additionally, I don't get a anti-adblock message on that URL with just this list enable. Must be something else that's causing it.

**Closed by hoshsadiq** 2018-05-09 20:42 UTC
