### ISSUE TITLE
Coinpot

### ISSUE THREAD

**Issue by ualmeida55** [hoshsadiq/adblock-nocoin-list#63] opened 2017-12-07 23:49 UTC
Hey, my AV (Eset IS) asked me to block a request from this site http://psarips.com, that was coming from this domain https://coinpot.co/mine/bitcoincore/?ref=CC037A58B367&mode=widget.

Hope I can help.

Great Job BTW.

**Comment by hoshsadiq** [comment] 2017-12-09 16:43
Can't reproduce with the latest filter list. Can you update the list and check again?

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/600045/33797447-f9f790f8-dcff-11e7-8025-5587a98c4af8.png">

**Comment by ualmeida55** [comment] 2017-12-09 18:19
I can't find the coinpot URL on the source code of site anymore. Guess it was removed.

**Comment by hoshsadiq** [comment] 2017-12-09 18:28
No worries. I'm going to close this. Feel free to comment on here again if/when it happens again.

**Closed by hoshsadiq** 2017-12-09 18:28 UTC
