### ISSUE TITLE
github.io blocked

### ISSUE THREAD

**Issue by acthp** [hoshsadiq/adblock-nocoin-list#312] opened 2018-10-15 20:41 UTC
rawgit is shutting down, so we moved some static assets to git pages, but this list is apparently blocking everything github.io. This seems very broken. What's the intent?

**Comment by graymalkin** [comment] 2018-10-15 22:15
Looks like that is a bug that's appeared in easylist too, fixed with this tweak: https://github.com/easylist/easylist/commit/536b5ece1fa1cced0ea2144c9a22a5b124062e2f

**Comment by acthp** [comment] 2018-10-15 23:28
@graymalkin That fix narrows it to cross-domain web assembly files? The rule still seems pretty odd, both because web assembly is not inherently crypto, and because there are many other cdns that will serve these same github files, so this rule doesn't actually block bad behavior.

**Comment by smed79** [comment] 2018-10-16 02:09
> this list is apparently blocking everything

It should not have a problem for `github.io` because of the [$third-party](https://adblockplus.org/en/filters#options) option specified in the filter.
Provide an example and describe how to reproduce.

(_reference [https://forums.lanik.us/viewtopic.php?f=64&t=40630](https://forums.lanik.us/viewtopic.php?f=64&t=40630&hilit=github+coin+miners)_)


@ryanbr fyi.

**Comment by acthp** [comment] 2018-10-16 16:38
does $third-party mean cross-domain? We use cross-domain requests for data integration from disparate sources. I can't easily provide a failing example w/o breaking our site, but if you visit xenabrowser.net, you will see three githubusercontent.com requests for json data that were being blocked when they were requested from github.io, e.g. defaultPhenotype.json.

**Comment by smed79** [comment] 2018-10-16 17:20
> does $third-party mean cross-domain?

I mean, `$third-party` will not affect first party sites (e.g. `subdomain.github.io`)

> if you visit xenabrowser.net, [...] data that were being blocked when they were requested from github.io

  I see only `google-analytics.com/analytics.js` blocked by EasyPrivacy https://i.imgur.com/nTzfJH1.png

> I can't easily provide a failing example

Until github fix this issue (by stopping abuse) this filter will stay. So if you want us to add exceptions for the broken sites, you have to provide an examples.

**Comment by hoshsadiq** [comment] 2018-10-18 20:55
@acthp do you have an example page that we can investigate?

**Comment by ryanbr** [comment] 2018-10-22 06:34
If you look through https://github.com/xd4rker/MinerBlock/blob/master/assets/filters.txt  you'll see plenty of github.io hosted coin miners, the moment you get github to close one, it'll just respawn under a new name.

**Comment by hoshsadiq** [comment] 2018-10-29 16:38
I will close this, if you want to continue the discussion, and feel free to do so.

**Closed by hoshsadiq** 2018-10-29 16:38 UTC
